marid:
  image: olivernadj/marid
  volumes:
    - ./etc/marid-proxy.conf:/etc/marid.conf
    - ./scripts:/var/lib/scripts
  environment:
    CONF_PATH: '/etc/marid.conf'
    SCRIPTS_DIR: '/var/lib/scripts'
    http_proxy: 'http://netproxy1.loc:8080'
    https_proxy: 'http://netproxy1.loc:8080'